### ISSUE TITLE
Chrome / Opera / Vivaldi potential?

### ISSUE THREAD

**Issue by EC-O-DE** [hoyang/browse-later#1]
Chrome / Opera / Vivaldi potential? I wonder :)

**Comment by hoyang** [comment]
Tried, can't use 'browser_action' and 'page_action' together in Google Chrome, may include Opera and Vivaldi.  😞

**Comment by hoyang** [comment]
Hi, Google Chrome branch added. 🤣

**Comment by hoyang** [comment]
chrome branch added
