### ISSUE TITLE
Update en_US string

### ISSUE THREAD

**Issue by ivanruvalcaba** [hoyang/browse-later#11]
Nice day!

When I was translating the strings into Spanish, I found that the following string still refers to the previous icon:

https://github.com/hoyang/browse-later/blob/f4187d345f6d485a87a20d789374d0c2447d4ce8/_locales/en/messages.json#L53

It may be necessary to carry out a small revision.

Best regards.

**Comment by hoyang** [comment]
Thank you!
i'll merge your pull-request later and fix this message string then submit new version to AMO.

: )

**Comment by hoyang** [comment]
Hi, the en locale was updated and pushed to dev branch, can you re-translate this line and push again? sorry i'm know-nothing about Spanish, even though Google translate...

and es locale merged, after this translate update, i'll release a new version to AMO.

Thank you!

**Comment by ivanruvalcaba** [comment]
Nice day!

I have just sent you a pull request solving this issue, so I will take the liberty of closing the thread.

Best regards.

**Comment by hoyang** [comment]
Thank you! version 3.1.2 was submited to AMO.

**Comment by ivanruvalcaba** [comment]
You are welcome! Thanks to you too for your hard work. Go ahead!

Best regards.
