### ISSUE TITLE
update es locale before new version release

### ISSUE THREAD

**Issue by hoyang** [hoyang/browse-later#14]
Hi, @ivanruvalcaba , can you help to update the Spanish/ES locale for new added translate messages?

the three line of text is:
- tabItemGroupOpenAllTitle
- tabItemGroupOpenAllNewWindowTitle
- browseLaterAllTabGroupMenu

in dev branch.

Thank you!

**Comment by ivanruvalcaba** [comment]
For sure! I'm in!

Best regards.

---
Fingerprint: 49AA 091A CBF9 632E BD99 9BF2 32D9 E18C 3D99 B685

Keybase: https://ivanruvalcaba.keybase.pub/

**Comment by ivanruvalcaba** [comment]
You have my pull request on the door 😄. The issue can now be closed!

Best regards.

**Comment by hoyang** [comment]
Thank you!

i'll close this issue and submit a new version to AMO.
