### ISSUE TITLE
[Feature Request] Option to keep tab open after clicking Browse Later icon

### ISSUE THREAD

**Issue by mjr66** [hoyang/browse-later#18]
At the moment, when you click on the Browse Later icon in the address bar, to add a new page to the Browse Later list, it immediately closes the current tab. Could you please add a setting which lets you keep the current tab open (as well as adding it to the list)? Thank you!

Sorry if this is already possible somehow, but I have missed something!

**Comment by hoyang** [comment]
Thank you for your feedback!

okay, i'll add this into next release version, before middle-Dec, now i'm involved many deadline... ass in fire.

**Comment by mjr66** [comment]
Thanks! Good luck with the deadline :)

**Comment by hoyang** [comment]
4.0.1beta submitted to AMO, so this issue can be closed.

**Comment by hoyang** [comment]
sorry for a extremely long time wait.
