### ISSUE TITLE
[Feature Request] Store Video playback position on select sites

### ISSUE THREAD

**Issue by FSMaxB** [hoyang/browse-later#19]
It would be nice to store the playback position on Video sites. For example on YouTube where the playback position can easily be embedded in the URL.

Like the addon [resumeLater](https://github.com/puppe/resumelater).

**Comment by hoyang** [comment]
Thank you for your suggestion!

Yes, we can, but i'm very busy before mid-Dec, after some deadline gone, i'll try to deal this and other issues.

**Comment by hoyang** [comment]
done
