### ISSUE TITLE
Choose to hide the counter when the list is empty

### ISSUE THREAD

**Issue by Reedo0910** [hoyang/browse-later#2]
Very nice work. 👍 
But it would be better if I can choose to hide the counter when the 'Browse later' list is empty, instead of showing 0 at the corner. ( Just like the way Stylus and Adblock do)
Because the counter is quite noticeable, and if there's nothing to remind me, I'd like to hide the counter 😄

**Comment by hoyang** [comment]
Thanks for your feedback, okay, if list empty, the counter will hide next release, may be this weekend.

**Comment by hoyang** [comment]
Version 2.6 released to AMO, so this issue can be closed.
