### ISSUE TITLE
Not working on Firefox 64.0b4?

### ISSUE THREAD

**Issue by hmijail** [hoyang/browse-later#22]
The first time I click on the toolbar button in any page it says something about whipping llamas' asses :P. Next click produces an empty window. I don't see any other way of interacting with the add-on.

**Comment by hoyang** [comment]
You should save some page first. the button is inside the right side of address bar in any tab.

**Comment by hmijail** [comment]
Aha, I see. Thank you and sorry for the confusion.

As an excuse, I'll say that I was mislead by the empty window that appeared on the second click; it made me think that the current page was being added but the list wasn't shown. But if anything that should be a new issue I guess.
