### ISSUE TITLE
UI & UX improvement

### ISSUE THREAD

**Issue by Reedo0910** [hoyang/browse-later#3]
I find it difficult to tap on the list item while using the tablet, and I think there can be some UX & UI improvements
**Before**
![before](https://user-images.githubusercontent.com/19267441/30051264-ee298b24-9253-11e7-9d2f-aabff08bc214.png)

So I have a Browse-Later redesign here
**After**
![after](https://user-images.githubusercontent.com/19267441/30052023-b31f8044-9256-11e7-82f9-17d994a87315.png)

What I have done:
1. Adding some simple icons to improve user experience.
2. Adding more padding to the list items and also to the icons
3. Change COPY TABS URL to REMOVE ALL, because I think the latter one is more commonly used
4. Add 2 buttons ( copy url & remove) to the end of each list item. 
5. Add favicon to the front of the list item, makes them easier to distinguish.

And what about a more eye-catching icon for Browse-Later?
![tab_unselected_128px_1182293_easyicon net](https://user-images.githubusercontent.com/19267441/30052333-aa08d9fa-9257-11e7-8989-395659fdabf2.png)

You can download the resource here:
[img.zip](https://github.com/hoyang/browse-later/files/1276612/img.zip)

**Comment by hoyang** [comment]
Extremely thanks, i will try within this weekend, it's looks amazing, make it reborn.

**Comment by Reedo0910** [comment]
You're welcome. 
And I've made some adjustments to make it look more friendly.
![after](https://user-images.githubusercontent.com/19267441/30073449-67de63d0-92a0-11e7-907f-559fca468dd0.png)
**Pay attention to the length of the long text automatically hidden control and the alignment of the elements**

You can download the psd file here
[resource.zip](https://github.com/hoyang/browse-later/files/1278293/resource.zip)

Looking forward to the new-looking Browse-Later

**Comment by hoyang** [comment]
Thanks, i will do my best for pixel-perfect as your design.

**Comment by hoyang** [comment]
Hi, may there are little problem, the green cornor at the icon covered by the green badge text and then only dotted line shown.
![screen shot 2017-09-06 at 21 02 48](https://user-images.githubusercontent.com/1560898/30113457-592cc9ce-9347-11e7-903b-7755445a48ed.png)

how about move the such cutie corner to left side?

**Comment by Reedo0910** [comment]
Well, let me adjust it as well.

**Comment by Reedo0910** [comment]
I drew a new icon for Browse-Later that combines the clock and the newspaper.

And the new design follows the guide in [Firefox Photon Design System]( http://design.firefox.com/photon/visual/icons.html)

I also made two themes for the icon ( light & dark) following the guideline.

**Light**
![browse-later-icon-light](https://user-images.githubusercontent.com/19267441/30125491-1f71a104-936b-11e7-874d-7f99852fb878.png)

**Dark**
![browse-later-icon-dark](https://user-images.githubusercontent.com/19267441/30125483-14ec201a-936b-11e7-8b3b-21ad007f6904.png)

Does it look better now?

*I found that the icon whose size is smaller than 32px has lost a lot of the details, so it's recommended to use the larger ones*

Download them here
[icon.zip](https://github.com/hoyang/browse-later/files/1282071/icon.zip)

**Comment by hoyang** [comment]
Hi, after a busy weekend, now Browse-later looks like that:

![empty](https://user-images.githubusercontent.com/1560898/30249193-80dfd072-9669-11e7-9552-c6559defb31a.png)
![tabs-saved](https://user-images.githubusercontent.com/1560898/30249194-80e17bde-9669-11e7-8db6-2fcc0f4e8fa9.png)

also a little problem there is: the newest icon with clock and newspapper may not looks like Firefox's builtin one, it's too many details inside 16*16 px so looks vague (or looks not so strong like firefox's one).

![icon](https://user-images.githubusercontent.com/1560898/30249208-f5f34394-9669-11e7-92b0-073e65e806fd.png)

sorry that i can't follow up every details your designed, and it's hard to do Firefox's dark/light theme detection, after many docs readed, a solution some one said is provide a SVG with monochronic color, and firefox will fill color suitable, BUT i knownothing about SVG just like Jon Snow. : (

---- ---- ---- ----

Do you have any advice?

**Comment by hoyang** [comment]
And this:

![screen shot 2017-09-10 at 23 13 15](https://user-images.githubusercontent.com/1560898/30250260-bfd0bac6-967d-11e7-8b81-3a0745a1a1a6.png)

**Comment by Reedo0910** [comment]
It looks much better now.  Really well done!
I designed the icon with the latest Firefox 57 (nightly) design language (Photon). 
But yeah, it looks really weird now.
Seems like I have to provide an SVG icon, and redesign the icon again for the 16 x 16 version.

Perhaps I can help you finish the UI part, because I am a front-end engineer, may be I can handle my own design better. Once I finish, I will use the pull request.

**Comment by hoyang** [comment]
And this is Google Chrome branch (prototype):

![screen shot 2017-09-11 at 00 18 01](https://user-images.githubusercontent.com/1560898/30250778-e28e51c8-9686-11e7-8373-e039dd097e5c.png)
![screen shot 2017-09-11 at 00 17 32](https://user-images.githubusercontent.com/1560898/30250779-e29096ae-9686-11e7-828d-cbecfeee146b.png)

**Comment by hoyang** [comment]
**Thank you for your help!**

do you have any suggestions about copy/delete’s icon? which looks better?

![trash](https://user-images.githubusercontent.com/1560898/30251094-fd43656c-968b-11e7-9a00-6167040a1e44.png)
![delete](https://user-images.githubusercontent.com/1560898/30251097-fd5ed02c-968b-11e7-8642-63b4edffaf06.png)
----
![copy](https://user-images.githubusercontent.com/1560898/30251096-fd474b28-968b-11e7-93bc-9def0cac0c63.png)
![copy_url](https://user-images.githubusercontent.com/1560898/30251095-fd43d47a-968b-11e7-85f4-030e229a1b46.png)

seems the copy icon has more blank border than delete icon.

----
[old](https://user-images.githubusercontent.com/1560898/30249194-80e17bde-9669-11e7-8db6-2fcc0f4e8fa9.png)
[new](https://github.com/hoyang/browse-later/issues/3#issuecomment-328349154)

**Comment by Reedo0910** [comment]
It seems like the "old" one is more suitable. ![](https://user-images.githubusercontent.com/1560898/30251096-fd474b28-968b-11e7-93bc-9def0cac0c63.png)
But the design has to be improved as well. I will take some time to think about it.

**Comment by hoyang** [comment]
Hi, i got a stupid idea: use a colorful icon, many others addon has a colorful icon so there are looks good with both Dark/Light theme.
see: [uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?src=search) and [Instant Translate](https://addons.mozilla.org/en-US/firefox/addon/instant-translate/reviews/?src=api)

**Comment by Reedo0910** [comment]
Sounds not bad 😄

**Comment by Reedo0910** [comment]
I have sent you my code by pulling requests.  I did my best to improve the UI.

There are some suggestions, which may make Browse-later more powerful:

1.  Do not close the pop-up box if someone just deleted a single tab (when there are other tabs in the list). Try just to remove that list item.

2. When someone right-clicks the tab, add the Browse-later option to the context menu (preferably with the option to "add all tabs to the Browse-later list")

3. Use a progressive JavaScript framework (such as Vue.js) to manipulate the DOM, maybe it will make your HTML more intuitive

4. Text internationalization with [i18n API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n)

Admiring your work : )

**Comment by hoyang** [comment]
thanks again, i'll merge your pull-request this week.

Q 1: Okay, i'll do it after merge your code.
Q 2: Ok, i'll do it after merge your code.
Q 3: May no, because it will makes AMO take long time to do review, i tried ReactJS and underscore.js in my first submit, a refusal got. :(    --    but i'll do some tidy for my code.
Q 4: Okay, i'll do it before next release submission.

**Comment by Reedo0910** [comment]
Yeah, I see.

However, this morning I used Vue to reconstruct the code. And I found that the Standalone version of Vue 2.0 would cause some CSP problems so that it could only be done with Vue 1.0 CSP-compliant build.
But if I use the Webpack to solve the CSP problems, that would only make the work more complicated.

I pushed my reconstructed version (with Vue 1.0 CSP-compliant build) to you just now, you can make a reference.

**Comment by hoyang** [comment]
Hi, i'll close this Issue and perform a new release submission (3.0.2) to AMO, it's a huge progressive with your help, version 3.0.1 is approved today, now it's looks pretty cute. thank you.

can you please open a new Issue for q1, q2, q3, q4 and Vue etc ?

**Comment by Reedo0910** [comment]
Yes, I'll be happy to see the new build.

And thank you very much for your patience
