### ISSUE TITLE
Don't add pinned tabs to the browse-later list

### ISSUE THREAD

**Issue by Reedo0910** [hoyang/browse-later#6]
Well, I really enjoyed the new “add all tabs to the list” button~ Thanks 

But I found that it would add my pinned tabs to the list and would remove them anyway.

I think if someone pinned his tabs, he might not want to remove them casually (not even want to “browse them later”). So it will be better if this new function could ignore the pinned tabs.

P.S. I’m so pleased to see the README, thank you so much

**Comment by hoyang** [comment]
This is very easy to fix, but some one (may AMO's robot) said this add-on is too frequency to do update, so i will push to AMO after this weekend.

**Comment by Reedo0910** [comment]
Right

**Comment by hoyang** [comment]
New version 3.0.3 approved by AMO, so this issue can be closed
