### ISSUE TITLE
A minor bug

### ISSUE THREAD

**Issue by Reedo0910** [hoyang/browse-later#7]
Feeling sorry to open an issue again.

But I found that when I clicked on the icon at the first time after rebooting the browser, the list panel wouldn't be popped up.

Then I had to click again to active it.

I believed it's a very minor bug(maybe some event listener things), but it'll definetly reduce the user experience.

**Comment by hoyang** [comment]
Yes, i'll catch this bug, and add a white background color for header area(if someone's browse-later list is long enough that transparent background is not looking good), after this weekend, and submit a new release to AMO.

and thank you of course!

**Comment by hoyang** [comment]
New version 3.0.4 submitted, so this issue can be closed.

**Comment by hoyang** [comment]
New version 3.0.4 submitted, so this issue can be closed.
